---
title: "Data Cleaning"
format: html
editor: visual
---

## Loading Libraries

```{r}
library(tidyverse)
library(ggplot2)
library(caret)

 
```

## Cleaning Data

```{r}

raw_data <- read.csv("Autism_Screening_Data.csv")
df <- raw_data[c(2:13,15,16,19,22)]
df_num <- raw_data[c(2:12)]

sapply(df_num, class)
df_num <- df_num|> 
  mutate_if(is.integer, as.numeric)
df_num$age <- as.numeric(df_num$age)



df_num$outcome[df$Class.ASD == "NO"] <- 0
df_num$outcome[df$Class.ASD == "YES"] <- 1

df_num$sex[df$gender == "f"] <- 0
df_num$sex[df$gender == "m"] <- 1

df_num$jundice[df$jundice == "no"] <- 0
df_num$jundice[df$jundice == "yes"] <- 1

df_num$asd.parent[df$austim == "no"] <- 0
df_num$asd.parent[df$austim == "yes"] <- 1

sapply(df_num, class)
```

Tutorial Code Begins

## SVM

```{r}
df_num <- df_num |>
  drop_na()

set.seed(1234)
intrain <- createDataPartition(y = df_num$outcome, p=0.7, list = FALSE)
training <- df_num[intrain,]
testing <- df_num[-intrain,]

dim(training)
dim(testing)

anyNA(df_num)

summary(df_num)

training[["outcome"]] = factor(training[["outcome"]])

trcrtl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)

svm_Linear <- train(outcome ~., data = training, method = "svmLinear", 
                    trControl=trcrtl, preProcess= c("center", "scale"),
                    tuneLength = 10)

svm_Linear

test_pred <- predict(svm_Linear, newdata = testing)
test_pred

confusionMatrix(table(test_pred, testing$outcome))

grid <- expand.grid(C = c(0, 0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 5))

svm_Linear_Grid <- train(outcome ~., data = training, method = "svmLinear",
                    trControl=trcrtl, preProcess= c("center", "scale"), 
                    tuneGrid = grid, tuneLength = 10)
svm_Linear_Grid
plot(svm_Linear_Grid)

test_pred_grid <- predict(svm_Linear_Grid, newdata = testing)
test_pred_grid

confusionMatrix(table(test_pred_grid, testing$outcome))

```

## Random Forrest 

```{r}

library(randomForest)
df_num <- df_num |>
  drop_na()


set.seed(100)
intrain <- createDataPartition(y = df_num$outcome, p=0.7, list = FALSE)
training_rf <- df_num[intrain,]
testing_rf <- df_num[-intrain,]

training_rf$outcome <- as.factor(training_rf$outcome)

bestmtry <- tuneRF(training_rf, training_rf$outcome, stepFactor = 1.2, improve = 0.01, trace = T, plot = T )

asd_forest <- randomForest(outcome~., data = training)
asd_forest

importance(asd_forest)
varImpPlot(asd_forest)

forest_pred1 <- predict(asd_forest, newdata = testing_rf, type = "class")
forest_pred1

confusionMatrix(table(forest_pred1,testing_rf$outcome))
    
```

## Logistic Regression

```{r}
instal



```
